openapi: 3.0.0

info:
  title: API for Task Management Application 
  version: 1.0.0


paths:
  # paths オブジェクト
  /users:
    # path item オブジェクト
    get: # GET
      # Operationオブジェクト
      tags:
        - users
      summary: Get all users.
      description: Returns an array of User model
      parameters: []
      responses: # レスポンス定義
        '200': # HTTP status
          description: A JSON array of User model
          content:
            application/json: # レスポンスの形式指定
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/User' # 参照するモデル
                example: # サンプルデータ
                  - user_id: 1
                    user_name: Alice
                    department: human resources
                  - user_id: 2
                    name: Bob
                    department: sales
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                    
    post: # POST
      tags: 
        - users
      summary: Create a new User
      description: Create a new User
      parameters: 
        - in: query
          name: user_name
          schema:
            type: string
          description: user name
        - in: query
          name: department
          schema:
            type: string
          description: user's belonging
      requestBody: # リクエストボディ
        description: user to create
        content:
          application/json:
            schema: # POSTするオブジェクト
              type: object
            example: 
              name: Chris
              department: Finance
      responses:
        '201':
          description: CREATED
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'


  /tasks:
    # path item オブジェクト
    get: # GET
      # Operationオブジェクト
      tags:
        - tasks
      summary: Get all tasks.
      description: Returns an array of Task model
      parameters: []
      responses: # レスポンス定義
        '200': # HTTP status
          description: A JSON array of Task model
          content:
            application/json: # レスポンスの形式指定
              schema: 
                type: array
                items:
                  $ref: '#/components/schemas/Task' # 参照するモデル
                example: # サンプルデータ
                  - task_id: 1
                    user_id: 1
                    task_name: make slides
                    status: not yet
                    deadline: 2022-09-30
                  - task_id: 2
                    user_id: 1
                    task_name: send files
                    status: not yet
                    deadline: 2022-09-30
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post: # POST
      tags: 
        - tasks
      summary: Create a new Task
      description: Create a new Task
      parameters: 
        - in: query
          name: user_id
          schema:
            type: integer
          description: the owner's id of the task
        - in: query
          name: task_name
          schema:
            type: string
          description: task name
        - in: query
          name: status
          schema:
            type: string
          description: status
        - in: query
          name: deadline
          schema:
            type: string
          description: deadline
      requestBody: # リクエストボディ
        description: task to create
        content:
          application/json:
            schema: # POSTするオブジェクト
              type: object
            example:
              user_id: 1
              task_name: send file
              status: new
              deadline: 2022-12-1
      responses:
        '201':
          description: CREATED
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          
  /users/{user_id}/tasks:
    get:
      tags:
        - taskSummary
      summary: Get tasks by user_id.
      description: Returns an array of Task_summary
      parameters: # リクエストパラメータ
        - name: user_id
          in: path # パラメータをパス内に含める
          description: user id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: A single Task_summary model
          content:
            application/json:
              schema: 
                type: object
                items:
                  $ref: '#/components/schemas/Task_summary'
                example:
                  user_name: Alice
                  department: human resources
                  task_name: make slides
                  status: not yet
                  deadline: 2022-9-30
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        
                  
                  
components:
  schemas: # スキーマオブジェクトの定義
    User: # モデル名
      type: object # 型
      required: # 必須フィールド
        - user_id
        - user_name
        - department
      properties:
        user_id: # プロパティ名
          type: integer # 型 
          format: int64 # フォーマット(int32, int64等)
          example: 1
        user_name:
          type: string
          example: John Smith
        department:
          type: string
          example: Human Resource

    Task:
      type: object
      required:
        - task_id
        - user_id
        - task_name
        - status
        - deadline
      properties:
        task_id:
          type: integer
          format: int64
          example : 1
        user_id:
          type: integer
          format: int64
          example: 1
        task_name:
          type: string
          example: make slides
        status:
          type: string
          example: not yet
        deadline:
          type: string
          example: 2022-06-16
          
          
    
    Task_summary:
      type: object
      required:
        - user_name
        - department
        - task_name
        - status
        - deadline
      properties:
        user_name:
          type: string
          example : John Smith
        department: 
          type: string
          example: human resources
        task_name:
          type: string
          example: make slides
        status:
          type: string
          example: not yet
        deadline:
          type: string
          example: 2022-06-16
          
    Error:
      type: object
      title: Error
      description: エラーオブジェクトの共通スキーマ
      properties:
        state:
          type: string
          description: エラーの種別
          example: TodoNotFound
          maxLength: 255
        message:
          type: string
          description: エラーメッセージ
          maxLength: 255
          example: Todoが1件も存在しません
          readOnly: true
      required:
        - state
        - message
          